services:
    wireguard:
        image: khademianx/wireguard-panel
        container_name: wireguard
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8880}:8000'
            - "${HTTPS_PORT:-8443}:8000"
            - '${WIREGUARD_PORT:-51820}:51820/udp'
        volumes:
            - '/opt/wireguard/.env:/app/.env'
            - '/opt/wireguard/data:/etc/wireguard'
            - '/opt/wireguard/keys:/app/storage/app/private/wireguard'
            - '/opt/wireguard/db:/app/database/sqlite'
            - 'caddy_data:/data'
            - 'caddy_config:/config'
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.all.src_valid_mark=1
        networks:
            - wireguard
        environment:
            - OCTANE_SERVER=frankenphp
        env_file:
            - .env

networks:
    wireguard:

volumes:
    caddy_data:
    caddy_config:
